var test             = require('tape')
  , inherits         = require('inherits')
  , ErrorStackParser = require('error-stack-parser')
  , errno            = require('./')

test('sanity checks', function (t) ***REMOVED***
  t.ok(errno.all, 'errno.all not found')
  t.ok(errno.errno, 'errno.errno not found')
  t.ok(errno.code, 'errno.code not found')

  t.equal(errno.all.length, 60, 'found ' + errno.all.length + ', expected 60')
  t.equal(errno.errno['-1'], errno.all[1], 'errno -1 not second element')

  t.equal(errno.code['UNKNOWN'], errno.all[1], 'code UNKNOWN not second element')

  t.equal(errno.errno[1], errno.all[3], 'errno 1 not fourth element')

  t.equal(errno.code['EOF'], errno.all[3], 'code EOF not fourth element')
  t.end()
***REMOVED***)

test('custom errors', function (t) ***REMOVED***
  const Cust = errno.create('FooNotBarError')
  const cust = new Cust('foo is not bar')

  t.equal(cust.name, 'FooNotBarError', 'correct custom name')
  t.equal(cust.type, 'FooNotBarError', 'correct custom type')
  t.equal(cust.message, 'foo is not bar', 'correct custom message')
  t.notOk(cust.cause, 'no cause')
  t.end()
***REMOVED***)

test('callstack', function (t) ***REMOVED***
  const MyError = errno.create('MyError')

  function lastFunction (ErrorType, cb) ***REMOVED***
    process.nextTick(cb, new ErrorType('oh noes!'))
  ***REMOVED***

  function secondLastFunction (ErrorType, cb) ***REMOVED***
    lastFunction(ErrorType, cb)
  ***REMOVED***

  function testFrames (t) ***REMOVED***
    return function (err) ***REMOVED***
      const stack = ErrorStackParser.parse(err)
      t.same(stack[0].functionName, 'lastFunction', 'last stack frame ok')
      t.same(stack[1].functionName, 'secondLastFunction', 'second last stack frame ok')
      t.end()
    ***REMOVED***
  ***REMOVED***

  t.test('custom error, default prototype', function (t) ***REMOVED***
    secondLastFunction(MyError, testFrames(t))
  ***REMOVED***)

  t.test('custom error, custom prototype', function (t) ***REMOVED***
    const MyError2 = errno.create('MyError2', MyError)
    secondLastFunction(MyError2, testFrames(t))
  ***REMOVED***)

  t.test('custom error, using inheritance', function (t) ***REMOVED***
    const CustomError = errno.custom.CustomError

    function MyError3 (message, cause) ***REMOVED***
      CustomError.call(this, message, cause)
    ***REMOVED***

    inherits(MyError3, CustomError)

    secondLastFunction(MyError3, testFrames(t))
  ***REMOVED***)
***REMOVED***)
